default: &default
  adapter: mysql2
  encoding: utf8mb4
  username: root
  password: password
  host: db

development:
  <<: *default
  database: blog_app_development

test:
  <<: *default
  database: ruby_test

production:
  <<: *default
  database: ruby_production